{% set name = "devpi-common" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devpi-common-{{ version }}.tar.gz
  sha256: f8e01b4f6df080f62284cce58c5bb1ce1e869b0c234aac7ad135609745fc173d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - lazy
    - packaging >=22
    - python >=3.7
    - requests >=2.3.0

test:
  imports:
    - devpi_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/devpi/devpi
  dev_url: https://github.com/devpi/devpi/tree/main/common
  doc_url: http://doc.devpi.net/
  summary: Devpi utilities jointly used by devpi-server and devpi-client
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
